import { SELECTORS } from '$utils/constants';
import { formatCode, appendHeadScript } from '$utils/domUtils';

// previous index.ts for reference
window.Webflow ||= [];
window.Webflow.push(async () => {
  const codeListings = document.querySelectorAll<HTMLDivElement>(SELECTORS.CODE_LISTING);
  const componentCopyButtons = document.querySelectorAll<HTMLAnchorElement>(
    `[${SELECTORS.COPY_COMPONENT}]`
  );

  componentCopyButtons.forEach(async (componentCopyButton) => {
    componentCopyButton.addEventListener('click', async () => {
      const url = componentCopyButton.getAttribute(SELECTORS.COPY_COMPONENT);
      if (!url) return;

      const resp = await fetch(url);
      const wfJson = await resp.json();

      try {
        document.addEventListener('copy', (e) => {
          copyButtonClicked(e, wfJson);
        });
        document.execCommand('copy');
      } catch (e) {
      } finally {
        document.removeEventListener('copy', (e) => {
          copyButtonClicked(e, wfJson);
        });
      }

      const textDiv = componentCopyButton.lastChild as HTMLDivElement;
      const previousText = textDiv.innerText;
      textDiv.innerText = 'Copied!';

      setTimeout(() => {
        textDiv.innerText = previousText;
      }, 2000);
    });
  });

  await Promise.all(
    [...codeListings].map(async (codeListing) => {
      const url = codeListing.getAttribute('url');
      const copyTrigger = codeListing.parentElement?.querySelector<HTMLAnchorElement>(
        '[fs-copyclip-element="click"]'
      );
      if (!url || !copyTrigger) return;

      const resp = await fetch(url);
      const code = await resp.text();

      copyTrigger.addEventListener('click', function (e) {
        e.preventDefault();

        const textDiv = copyTrigger.lastChild as HTMLDivElement;
        if (!textDiv) return;

        const previousText = textDiv.innerText;
        textDiv.innerText = 'Copied!';

        setTimeout(() => {
          textDiv.innerText = previousText;
        }, 2000);

        navigator.clipboard.writeText(code);
      });

      codeListing.innerHTML = formatCode(code);
    })
  );

  appendHeadScript(SELECTORS.CODE_HIGHLIGHT_ATTR_URL);
});

const copyButtonClicked = (event: ClipboardEvent, wfJson: JSON) => {
  event.clipboardData?.setData('application/json', JSON.stringify(wfJson));
  event.preventDefault();
};

const json = `{
  "type": "@webflow/XscpData",
  "payload": {
    "nodes": [
      {
        "_id": "7350ca48-0033-c2f3-ebd5-ef102ce282a9",
        "type": "Block",
        "tag": "div",
        "classes": ["4a44386d-cf38-1623-cdcd-312d92de0e1a"],
        "children": ["f4f07580-05bd-b293-b922-1fecfcad042c"],
        "data": {
          "search": { "exclude": false },
          "xattr": [],
          "text": false,
          "displayName": "",
          "attr": { "id": "" },
          "visibility": { "conditions": [] },
          "tag": "div"
        }
      },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad042c",
        "type": "Block",
        "tag": "div",
        "classes": ["23b24c2e-94b0-24a0-977f-440935ec54a8"],
        "children": [
          "f4f07580-05bd-b293-b922-1fecfcad0430",
          "f4f07580-05bd-b293-b922-1fecfcad0432",
          "f4f07580-05bd-b293-b922-1fecfcad0437"
        ],
        "data": {
          "search": { "exclude": false },
          "xattr": [],
          "text": false,
          "displayName": "",
          "attr": { "id": "" },
          "visibility": { "conditions": [] },
          "tag": "div"
        }
      },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad0430",
        "type": "Heading",
        "tag": "h4",
        "classes": [],
        "children": ["f4f07580-05bd-b293-b922-1fecfcad0431"],
        "data": {
          "tag": "h4",
          "displayName": "",
          "attr": { "id": "" },
          "xattr": [],
          "search": { "exclude": false },
          "visibility": { "conditions": [] }
        }
      },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad0431",
        "text": true,
        "v": "The year is being generated by javascript!"
      },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad0432",
        "type": "Block",
        "tag": "div",
        "classes": [],
        "children": [
          "f4f07580-05bd-b293-b922-1fecfcad0433",
          "f4f07580-05bd-b293-b922-1fecfcad0436"
        ],
        "data": {
          "search": { "exclude": false },
          "xattr": [],
          "text": true,
          "displayName": "",
          "attr": { "id": "" },
          "visibility": { "conditions": [] },
          "tag": "div"
        }
      },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad0433",
        "text": true,
        "v": "You'll see 2015 in designer and "
      },
      { "_id": "f4f07580-05bd-b293-b922-1fecfcad0436", "text": true, "v": "on thepublished page" },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad0437",
        "type": "Block",
        "tag": "div",
        "classes": ["c73deda7-e937-fffb-30de-29f481f5392e"],
        "children": [
          "f4f07580-05bd-b293-b922-1fecfcad0438",
          "f4f07580-05bd-b293-b922-1fecfcad043a"
        ],
        "data": {
          "search": { "exclude": false },
          "xattr": [],
          "text": false,
          "displayName": "",
          "attr": { "id": "" },
          "visibility": { "conditions": [] },
          "tag": "div"
        }
      },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad0438",
        "type": "Block",
        "tag": "div",
        "classes": ["156fdf03-81ea-eb32-9dab-5ba72b209eb8"],
        "children": ["f4f07580-05bd-b293-b922-1fecfcad0439"],
        "data": {
          "search": { "exclude": false },
          "xattr": [],
          "text": true,
          "displayName": "",
          "attr": { "id": "" },
          "visibility": { "conditions": [] },
          "tag": "div"
        }
      },
      { "_id": "f4f07580-05bd-b293-b922-1fecfcad0439", "text": true, "v": "Finsweet, Inc." },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad043a",
        "type": "Block",
        "tag": "div",
        "classes": [],
        "children": [
          "f4f07580-05bd-b293-b922-1fecfcad043b",
          "f4f07580-05bd-b293-b922-1fecfcad043c",
          "f4f07580-05bd-b293-b922-1fecfcad043e"
        ],
        "data": {
          "search": { "exclude": false },
          "xattr": [],
          "text": true,
          "displayName": "",
          "attr": { "id": "" },
          "visibility": { "conditions": [] },
          "tag": "div"
        }
      },
      { "_id": "f4f07580-05bd-b293-b922-1fecfcad043b", "text": true, "v": "Copyright " },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad043c",
        "type": "Span",
        "tag": "span",
        "classes": ["6cd6e22e-87ac-5916-3cb7-4cd7333a18ee", "48d52af8-d518-8f2c-72a6-deffe8326882"],
        "children": ["f4f07580-05bd-b293-b922-1fecfcad043d"],
        "data": {
          "displayName": "",
          "attr": { "id": "" },
          "xattr": [{ "name": "fs-hacks-element", "value": "year" }],
          "search": { "exclude": false },
          "visibility": { "conditions": [] }
        }
      },
      { "_id": "f4f07580-05bd-b293-b922-1fecfcad043d", "text": true, "v": "2015" },
      {
        "_id": "f4f07580-05bd-b293-b922-1fecfcad043e",
        "text": true,
        "v": ", Dinner reservations reserved"
      }
    ],
    "styles": [
      {
        "_id": "4a44386d-cf38-1623-cdcd-312d92de0e1a",
        "fake": false,
        "type": "class",
        "name": "example_block",
        "namespace": "",
        "comb": "",
        "styleLess": "display: grid; width: 100%; padding-top: 3rem; padding-right: 3rem; padding-bottom: 3rem; padding-left: 3rem; grid-auto-columns: 1fr; grid-column-gap: 2rem; grid-row-gap: 2rem; grid-template-columns: 1fr; grid-template-rows: auto; border-top-style: solid; border-top-width: 1rem; border-top-color: hsla(219.99999999999997, 4.68%, 7.18%, 1.00); border-right-style: solid; border-right-width: 1rem; border-right-color: hsla(219.99999999999997, 4.68%, 7.18%, 1.00); border-bottom-style: solid; border-bottom-width: 1rem; border-bottom-color: hsla(219.99999999999997, 4.68%, 7.18%, 1.00); border-left-style: solid; border-left-width: 1rem; border-left-color: hsla(219.99999999999997, 4.68%, 7.18%, 1.00); border-top-left-radius: 0.25rem; border-top-right-radius: 0.25rem; border-bottom-left-radius: 0.25rem; border-bottom-right-radius: 0.25rem; background-color: hsla(219.99999999999997, 5.66%, 10.39%, 1.00);",
        "variants": {
          "small": {
            "styleLess": "padding-top: 1.5rem; padding-right: 1.5rem; padding-bottom: 1.5rem; padding-left: 1.5rem;"
          },
          "tiny": {
            "styleLess": "padding-top: 1.5rem; padding-right: 1.5rem; padding-bottom: 1.5rem; padding-left: 1.5rem;"
          }
        },
        "children": [],
        "createdBy": "57380bb111b9c4825e447f0d",
        "selector": null
      },
      {
        "_id": "23b24c2e-94b0-24a0-977f-440935ec54a8",
        "fake": false,
        "type": "class",
        "name": "demo-7_component",
        "namespace": "",
        "comb": "",
        "styleLess": "display: grid; justify-items: stretch; grid-auto-columns: 1fr; grid-column-gap: 1rem; grid-row-gap: 1rem; grid-template-columns: 1fr; grid-template-rows: auto; text-align: center;",
        "variants": {},
        "children": [],
        "createdBy": "54441c96b0981db6504faf03",
        "selector": null
      },
      {
        "_id": "c73deda7-e937-fffb-30de-29f481f5392e",
        "fake": false,
        "type": "class",
        "name": "demo-7_content",
        "namespace": "",
        "comb": "",
        "styleLess": "display: flex; padding-top: 1.5rem; padding-right: 1.5rem; padding-bottom: 1.5rem; padding-left: 1.5rem; flex-direction: row; justify-content: space-between; align-items: center; background-color: hsla(0, 0.00%, 24.43%, 1.00); text-align: left;",
        "variants": {
          "small": { "styleLess": "flex-direction: column; align-items: flex-start;" }
        },
        "children": [],
        "createdBy": "54441c96b0981db6504faf03",
        "selector": null
      },
      {
        "_id": "156fdf03-81ea-eb32-9dab-5ba72b209eb8",
        "fake": false,
        "type": "class",
        "name": "demo-7_text",
        "namespace": "",
        "comb": "",
        "styleLess": "flex-grow: 1; flex-shrink: 1; flex-basis: 0%;",
        "variants": {},
        "children": [],
        "selector": null
      },
      {
        "_id": "48d52af8-d518-8f2c-72a6-deffe8326882",
        "fake": false,
        "type": "class",
        "name": "demo-7_year",
        "namespace": "",
        "comb": "",
        "styleLess": "",
        "variants": {},
        "children": [],
        "createdBy": "54441c96b0981db6504faf03",
        "selector": null
      }
    ],
    "assets": [],
    "ix1": [],
    "ix2": { "interactions": [], "events": [], "actionLists": [] }
  },
  "meta": {
    "unlinkedSymbolCount": 0,
    "droppedLinks": 0,
    "dynBindRemovedCount": 0,
    "dynListBindRemovedCount": 0,
    "paginationRemovedCount": 0
  }
}`;
const obj = 